import json
rows = []
def add(rule, gap, path, repl, status, quote, why):
    rows.append({'team_rule_id': rule, 'gap_fact': gap, 'path': path, 'replacement': repl, 'evidence_quote': quote, 'status': status, 'rationale': why})
EQ = 'eq'
D1 = add('D040-r001', 'unresolved_legal_evidence_D040_1', 'logic.coverage.all[1]', {'fact': 'landlord_terminating_tenancy', 'op': EQ, 'value': True}, 'resolved', 'It prohibits terminations of tenancies without just cause and requires relocation assistance for no-fault evictions.', 'Text nennt Kuendigung ohne just cause als operative Bedingung; kanonischer Fakt landlord_terminating_tenancy existiert bereits.')
D2 = add('D040-r006', 'unresolved_legal_evidence_D040_6', 'logic.coverage.all[1]', None, 'resolved', 'Beginning August 20, 2025, landlords must post a Notice of Right to Counsel in a conspicuous common area of the residential building where the tenant resides.', 'Redundant: LA + residential_building decken die Textbedingung ab; Pflichtdetails (Tenancy-Beginn, Eviction-Notice) sind Requirement, kein Coverage-Gate. Leaf ersatzlos streichen.')
D3 = add('D041-r002', 'unresolved_legal_evidence_D041_2', 'logic.coverage.all[1]', {'fact': 'rent_increase_notice_date', 'op': 'gte', 'value': '2026-02-02'}, 'resolved', 'Effective February 2, 2026, the landlord can no longer include an additional percentage increase for utilities.', 'Stichtag 2026-02-02 fehlt in Coverage; Muster wie D041-r005 mit kanonischem Fakt rent_increase_notice_date.')
D4 = add('D041-r003', 'unresolved_legal_evidence_D041_3', 'logic.coverage.all[1]', {'fact': 'rent_increase_notice_date', 'op': 'gte', 'value': '2026-02-02'}, 'resolved', 'Effective February 2, 2026, an additonal 10% increase for an additional dependent added to the tenancy is no longer permitted.', 'Gleicher Stichtag wie D041-r002 (Typo additonal steht so im Korpus); kanonischer Datumsfakt.')
D5 = add('D041-r004', 'unresolved_legal_evidence_D041_4', 'logic.coverage.all[1]', None, 'open', 'However, a 10% for an additional tenant is allowed (not a dependent) if moves into a rental unit: Landlords can increase the rent within 60 days of learning about the additional tenant.', 'Offen: 60-Tage-Fenster ab Kenntnis braucht Referenzdatum; kein kanonischer Fakt dafuer. Zusaetzlicher Mieter + Nicht-Dependent sind bereits abgedeckt, Leaf nicht er silent streichen (wuerde ueber-generalisieren).')
D6 = add('D041-r005', 'unresolved_legal_evidence_D041_5', 'logic.coverage.all[1]', None, 'resolved', 'Effective March 30, 2020, through January 31, 2024, rent increases are prohibited for rental units subject to the Rent Stabilization Ordinance (RSO).', 'Redundant: Zeitraum 2020-03-30 bis 2024-01-31 steht bereits als gte/lte-Leaves in Coverage. Leaf ersatzlos streichen.')
D7 = add('D041-r007', 'unresolved_legal_evidence_D041_7', 'logic.coverage.all[1]', None, 'open', 'The landlord may pass through 50% of the fee to the tenant every month rather than once a year. A 30-day notice must be given to the tenant to collect a rental surcharge of $1.61.', 'Offen: Erlaubnis zur monatlichen Umlage + 30-Tage-Notice lassen sich mit keinem kanonischen Fakt ausdruecken. Streichen wuerde die Regel auf alle RSO-Units verallgemeinern.')
D8 = add('D041-r008', 'unresolved_legal_evidence_D041_8', 'logic.coverage.all[1]', None, 'open', 'Effective January 1, 2022, a landlord may collect 1/12 of 50% of the annual Systematic Code Enforcement Fee from the tenant of the rental unit per month.', 'Offen: SCEP-Umlagehandlung hat keinen kanonischen Fakt. Nichts erfunden.')
D9 = add('D041-r009', 'unresolved_legal_evidence_D041_9', 'logic.coverage.all[1]', None, 'resolved', 'A $3.00 surcharge may be added to the rent for the installation and cost of a hard-wired smoke detector or a combination smoke/carbon monoxide detector.', 'Redundant: smoke_detector_installed steht bereits in Coverage und traegt die Textbedingung (Umbruch smoke/carbon im Korpus normalisiert). Leaf streichen.')
D10 = add('D041-r010', 'unresolved_legal_evidence_D041_10', 'logic.coverage.all[1]', {'fact': 'at_fault_just_cause_ground_exists', 'op': EQ, 'value': True}, 'resolved', 'Tenant is at-fault. Failure to pay rent. Failure to fix or address a violation of the rental agreement. Creating a nuisance or causing damage to the rental unit.', 'Coverage hatte nur RSO-Status; at-fault-Grund fehlt. Kanonischer Fakt at_fault_just_cause_ground_exists existiert.')
D11 = add('D041-r011', 'unresolved_legal_evidence_D041_11', 'logic.coverage.all[1]', {'fact': 'eviction_is_no_fault', 'op': EQ, 'value': True}, 'resolved', 'Tenant is not at-fault. The owner or immediate family member will move into the rental unit. Demolition and permanent removal from the rental market. Government order. Conversion to affordable housing.', 'No-fault-Charakter fehlt in Coverage; kanonischer Fakt eviction_is_no_fault existiert (vgl. D041-r013/r014). Auf 300 Zeichen gekuerzt.')
D12 = add('D041-r013', 'unresolved_legal_evidence_D041_13', 'logic.coverage.all[1]', None, 'resolved', 'No-fault evictions require the payment of relocation assistance.', 'Redundant: LA + RSO + eviction_is_no_fault decken die Bedingung voll ab. Leaf streichen.')
D13 = add('D041-r014', 'unresolved_legal_evidence_D041_14', 'logic.coverage.all[1]', None, 'resolved', 'Give the tenant a 30-day and 60-day written notice (some evictions require 120-day notice or up to a 1-year extension).', 'Fristen sind Requirement, kein Coverage-Gate; Coverage-Tripel ist vollstaendig. Leaf streichen.')
D14 = add('D041-r015', 'unresolved_legal_evidence_D041_15', 'logic.coverage.all[1]', None, 'resolved', 'Interest Payments on Security Deposits.', 'Duennes, aber wortwoertliches Heading-Zitat; Coverage (LA + RSO + security_deposit_collected) traegt die Regel. Leaf streichen.')
D15 = add('D041-r016', 'unresolved_legal_evidence_D041_16', 'logic.coverage.all[1]', None, 'resolved', 'Even if your property is not covered under the Rent Stabilization Ordinance, you and your tenants have rights and responsibilities under the Just Cause Ordinance.', 'Coverage (LA + unit_subject_to_rso=false) spiegelt den Text exakt. Leaf streichen.')
D16 = add('D042-r002', 'unresolved_legal_evidence_D042_2', 'logic.coverage.all[1]', {'fact': 'rent_increase_notice_date', 'op': 'gte', 'value': '2026-02-02'}, 'resolved', 'Beginning February 2, 2026, a landlord can no longer include any additional percentage increase for utilities.', 'Wie D041-r002, belegt aus D042-Text; kanonischer Datumsfakt.')
D17 = add('D042-r003', 'unresolved_legal_evidence_D042_3', 'logic.coverage.all[1]', None, 'open', 'State law requires landlords to provide 30 days written advance notice of rent increases of less than 10%.', 'Offen: kleiner-als-10-Prozent-Schwelle hat keinen kanonischen Fakt (rent_increase_planned allein waere Unter-Spezifikation). Nichts erfunden.')
D18 = add('D042-r003', 'unresolved_legal_condition_state_notice_exemption', 'logic.exemptions', None, 'open', '', 'Offen: D042-Text enthaelt keine Ausnahme zur 30-Tage-Notice; Exemption-Leaf unbelegt, kein Ersatz.')
D19 = add('D043-r006', 'unresolved_legal_evidence_D043_6', 'logic.coverage.all[1]', None, 'resolved', 'A landlord may offset the accumulated rent against any relocation assistance, unless the relocation assistance is owed because a termination of tenancy is required by a governmental agency order to vacate or comply with an issued order for an unpermitted dwelling.', 'Coverage (LA + relocation_assistance_required) plus Exemptions (beide agency/order-Fakten) decken Text voll ab. Leaf streichen.')
D20 = add('D043-r014', 'unresolved_legal_evidence_D043_14', 'logic.coverage.all[1]', None, 'resolved', 'If the City of Los Angeles Planning Department has approved a tentative parcel or tract map for a condominium conversion, the tenant may elect to relocate without receiving a Notice to Terminate Tenancy from the landlord.', 'Coverage-Fakt tentative_parcel_map_approved_for_condo_conversion spiegelt den Text exakt. Leaf streichen.')
json.dump(rows, open('/tmp/gapfix_B.json', 'w'), indent=1, ensure_ascii=False)
res = sum(1 for r in rows if r['status'] == 'resolved')
opn = sum(1 for r in rows if r['status'] == 'open')
md = []
md.append('# Gap-Resolution Batch B (D040-D043, Los Angeles RSO/JCO)')
md.append('')
md.append('Ergebnis: %d resolved, %d offen (von %d Gap-Leaves). DB nicht geschrieben; Fundstellen nur vorgeschlagen.' % (res, opn, len(rows)))
md.append('')
md.append('Hinweis: resolved + replacement=null heisst redundanter Platzhalter -> Leaf ersatzlos streichen und all-Kette kollabieren. Zitate <=300 Zeichen,Whitespace normalisiert.')
md.append('')
for r in rows:
    md.append('## ' + r['team_rule_id'] + ' / ' + r['gap_fact'])
    md.append('')
    md.append('Pfad: ' + r['path'] + ' | Status: ' + r['status'])
    md.append('')
    md.append('Entscheidung: ' + r['rationale'])
    md.append('')
    md.append('Ersatz: ' + (json.dumps(r['replacement']) if r['replacement'] else 'null (streichen bzw. offen)'))
    md.append('')
    md.append('Beleg: ' + ('> ' + r['evidence_quote'] if r['evidence_quote'] else '> (kein Beleg im Korpus)'))
    md.append('')
open('reports/gap_resolution_B.md', 'w').write(chr(10).join(md))
print('WROTE rows=%d resolved=%d open=%d' % (len(rows), res, opn))
